-- T1.1.c -- Anexos MAT/MATER HTML (8 tablas)
-- Non-destructive: CREATE TABLE IF NOT EXISTS, CREATE INDEX IF NOT EXISTS

-- raw_anexo_mat (9 cols)
create table if not exists public.raw_anexo_mat (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null
);
comment on table public.raw_anexo_mat is 'anexo_mat.html — A6.1.1 contratos MAT abastecimiento HTML (fuente preferida sobre raw_amat). T2.1.';
create index if not exists raw_anexo_mat_periodo_idx on public.raw_anexo_mat(anio, mes);
create index if not exists raw_anexo_mat_nemo_idx on public.raw_anexo_mat(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_mat_source_uidx on public.raw_anexo_mat(source_zip, source_file, source_row);
alter table public.raw_anexo_mat enable row level security;
drop policy if exists raw_anexo_mat_sel on public.raw_anexo_mat;
create policy raw_anexo_mat_sel on public.raw_anexo_mat for select to authenticated using (true);
drop policy if exists raw_anexo_mat_adm on public.raw_anexo_mat;
create policy raw_anexo_mat_adm on public.raw_anexo_mat for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_mat_plus (8 cols)
create table if not exists public.raw_anexo_mat_plus (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null
);
comment on table public.raw_anexo_mat_plus is 'anexo_mat_plus.html — A6 contratos Energia Plus. T2.14.';
create index if not exists raw_anexo_mat_plus_periodo_idx on public.raw_anexo_mat_plus(anio, mes);
create index if not exists raw_anexo_mat_plus_nemo_idx on public.raw_anexo_mat_plus(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_mat_plus_source_uidx on public.raw_anexo_mat_plus(source_zip, source_file, source_row);
alter table public.raw_anexo_mat_plus enable row level security;
drop policy if exists raw_anexo_mat_plus_sel on public.raw_anexo_mat_plus;
create policy raw_anexo_mat_plus_sel on public.raw_anexo_mat_plus for select to authenticated using (true);
drop policy if exists raw_anexo_mat_plus_adm on public.raw_anexo_mat_plus;
create policy raw_anexo_mat_plus_adm on public.raw_anexo_mat_plus for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_mat_renovable (6 cols)
create table if not exists public.raw_anexo_mat_renovable (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null
);
comment on table public.raw_anexo_mat_renovable is 'anexo_mat_renovable.html — A6.1.3.1 RENMER contratos renovables. T2.14.';
create index if not exists raw_anexo_mat_renovable_periodo_idx on public.raw_anexo_mat_renovable(anio, mes);
create index if not exists raw_anexo_mat_renovable_nemo_idx on public.raw_anexo_mat_renovable(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_mat_renovable_source_uidx on public.raw_anexo_mat_renovable(source_zip, source_file, source_row);
alter table public.raw_anexo_mat_renovable enable row level security;
drop policy if exists raw_anexo_mat_renovable_sel on public.raw_anexo_mat_renovable;
create policy raw_anexo_mat_renovable_sel on public.raw_anexo_mat_renovable for select to authenticated using (true);
drop policy if exists raw_anexo_mat_renovable_adm on public.raw_anexo_mat_renovable;
create policy raw_anexo_mat_renovable_adm on public.raw_anexo_mat_renovable for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_mat_cvt (8 cols)
create table if not exists public.raw_anexo_mat_cvt (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null
);
comment on table public.raw_anexo_mat_cvt is 'anexo_mat_cvt.html — A6 Cargo Variable de Transporte. T2.14.';
create index if not exists raw_anexo_mat_cvt_periodo_idx on public.raw_anexo_mat_cvt(anio, mes);
create index if not exists raw_anexo_mat_cvt_nemo_idx on public.raw_anexo_mat_cvt(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_mat_cvt_source_uidx on public.raw_anexo_mat_cvt(source_zip, source_file, source_row);
alter table public.raw_anexo_mat_cvt enable row level security;
drop policy if exists raw_anexo_mat_cvt_sel on public.raw_anexo_mat_cvt;
create policy raw_anexo_mat_cvt_sel on public.raw_anexo_mat_cvt for select to authenticated using (true);
drop policy if exists raw_anexo_mat_cvt_adm on public.raw_anexo_mat_cvt;
create policy raw_anexo_mat_cvt_adm on public.raw_anexo_mat_cvt for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_mat_cvt_plus (12 cols)
create table if not exists public.raw_anexo_mat_cvt_plus (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null,
  col_012 text null
);
comment on table public.raw_anexo_mat_cvt_plus is 'anexo_mat_cvt_plus.html — A6 CVT contratos Plus. T2.14.';
create index if not exists raw_anexo_mat_cvt_plus_periodo_idx on public.raw_anexo_mat_cvt_plus(anio, mes);
create index if not exists raw_anexo_mat_cvt_plus_nemo_idx on public.raw_anexo_mat_cvt_plus(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_mat_cvt_plus_source_uidx on public.raw_anexo_mat_cvt_plus(source_zip, source_file, source_row);
alter table public.raw_anexo_mat_cvt_plus enable row level security;
drop policy if exists raw_anexo_mat_cvt_plus_sel on public.raw_anexo_mat_cvt_plus;
create policy raw_anexo_mat_cvt_plus_sel on public.raw_anexo_mat_cvt_plus for select to authenticated using (true);
drop policy if exists raw_anexo_mat_cvt_plus_adm on public.raw_anexo_mat_cvt_plus;
create policy raw_anexo_mat_cvt_plus_adm on public.raw_anexo_mat_cvt_plus for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_mat_compromiso (26 cols)
create table if not exists public.raw_anexo_mat_compromiso (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null,
  col_012 text null,
  col_013 text null,
  col_014 text null,
  col_015 text null,
  col_016 text null,
  col_017 text null,
  col_018 text null,
  col_019 text null,
  col_020 text null,
  col_021 text null,
  col_022 text null,
  col_023 text null,
  col_024 text null,
  col_025 text null,
  col_026 text null
);
comment on table public.raw_anexo_mat_compromiso is 'anexo_mat_compromiso.html — Compromisos generador Res. ME 1085/17. T2.14.';
create index if not exists raw_anexo_mat_compromiso_periodo_idx on public.raw_anexo_mat_compromiso(anio, mes);
create index if not exists raw_anexo_mat_compromiso_nemo_idx on public.raw_anexo_mat_compromiso(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_mat_compromiso_source_uidx on public.raw_anexo_mat_compromiso(source_zip, source_file, source_row);
alter table public.raw_anexo_mat_compromiso enable row level security;
drop policy if exists raw_anexo_mat_compromiso_sel on public.raw_anexo_mat_compromiso;
create policy raw_anexo_mat_compromiso_sel on public.raw_anexo_mat_compromiso for select to authenticated using (true);
drop policy if exists raw_anexo_mat_compromiso_adm on public.raw_anexo_mat_compromiso;
create policy raw_anexo_mat_compromiso_adm on public.raw_anexo_mat_compromiso for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_mat_cont_delivery (13 cols)
create table if not exists public.raw_anexo_mat_cont_delivery (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null,
  col_012 text null,
  col_013 text null
);
comment on table public.raw_anexo_mat_cont_delivery is 'anexo_mat_cont_delivery.html — A6 Contratos Delivery entrega fisica. T2.14.';
create index if not exists raw_anexo_mat_cont_delivery_periodo_idx on public.raw_anexo_mat_cont_delivery(anio, mes);
create index if not exists raw_anexo_mat_cont_delivery_nemo_idx on public.raw_anexo_mat_cont_delivery(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_mat_cont_delivery_source_uidx on public.raw_anexo_mat_cont_delivery(source_zip, source_file, source_row);
alter table public.raw_anexo_mat_cont_delivery enable row level security;
drop policy if exists raw_anexo_mat_cont_delivery_sel on public.raw_anexo_mat_cont_delivery;
create policy raw_anexo_mat_cont_delivery_sel on public.raw_anexo_mat_cont_delivery for select to authenticated using (true);
drop policy if exists raw_anexo_mat_cont_delivery_adm on public.raw_anexo_mat_cont_delivery;
create policy raw_anexo_mat_cont_delivery_adm on public.raw_anexo_mat_cont_delivery for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_mat_cequip724 (6 cols)
create table if not exists public.raw_anexo_mat_cequip724 (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null
);
comment on table public.raw_anexo_mat_cequip724 is 'anexo_mat_cequip724.html — Capacidad Equivalente Res. SE 724 (1 fila/mes). T2.14.';
create index if not exists raw_anexo_mat_cequip724_periodo_idx on public.raw_anexo_mat_cequip724(anio, mes);
create index if not exists raw_anexo_mat_cequip724_nemo_idx on public.raw_anexo_mat_cequip724(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_mat_cequip724_source_uidx on public.raw_anexo_mat_cequip724(source_zip, source_file, source_row);
alter table public.raw_anexo_mat_cequip724 enable row level security;
drop policy if exists raw_anexo_mat_cequip724_sel on public.raw_anexo_mat_cequip724;
create policy raw_anexo_mat_cequip724_sel on public.raw_anexo_mat_cequip724 for select to authenticated using (true);
drop policy if exists raw_anexo_mat_cequip724_adm on public.raw_anexo_mat_cequip724;
create policy raw_anexo_mat_cequip724_adm on public.raw_anexo_mat_cequip724 for all to authenticated using (public.is_admin()) with check (public.is_admin());
