-- 20260429100600 — Identity + unique source index para raw_amat, raw_agum, raw_atra
--
-- PREREQUISITO: correr docs/preflight_t11_check.sql (checks 1-5) antes de aplicar.
-- Si 5a o 5b devuelven filas (duplicados), limpiar primero con el DELETE de 5c.
--
-- IDEMPOTENTE:
--   • Los DO blocks verifican pg_attribute.attidentity antes de ADD GENERATED.
--     No fallan si ya tienen identity (ej. si otra migration lo aplicó antes).
--   • setval se ejecuta solo si la secuencia existe (pg_get_serial_sequence != NULL).
--   • CREATE UNIQUE INDEX IF NOT EXISTS no falla si el índice ya existe.
--
-- ORDEN DE MIGRATIONS relevante:
--   20260426110000 — crea raw_amat, raw_agum (sin identity, sin unique source)
--   20260426123000 — crea raw_atra (sin identity, sin unique source)
--   20260429100000 — CREATE TABLE IF NOT EXISTS raw_atra con identity →
--                    si raw_atra ya existe por 20260426123000, la tabla no se toca.
--   20260429100600 — (este archivo) corrige identity en las 3 tablas existentes.

-- ─── raw_amat ────────────────────────────────────────────────────────────────

do $$
begin
  -- Agregar identity solo si todavía no la tiene
  if not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname  = 'raw_amat'
      and a.attname  = 'id'
      and a.attidentity in ('d', 'a')   -- 'd' = by default, 'a' = always
  ) then
    alter table public.raw_amat
      alter column id add generated by default as identity;
  end if;
end;
$$;

do $$
declare
  v_seq text;
  v_max bigint;
begin
  v_seq := pg_get_serial_sequence('public.raw_amat', 'id');
  if v_seq is not null then
    select coalesce(max(id), 0) + 1 into v_max from public.raw_amat;
    perform setval(v_seq, v_max, false);
  end if;
end;
$$;

-- ─── raw_agum ────────────────────────────────────────────────────────────────

do $$
begin
  if not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname  = 'raw_agum'
      and a.attname  = 'id'
      and a.attidentity in ('d', 'a')
  ) then
    alter table public.raw_agum
      alter column id add generated by default as identity;
  end if;
end;
$$;

do $$
declare
  v_seq text;
  v_max bigint;
begin
  v_seq := pg_get_serial_sequence('public.raw_agum', 'id');
  if v_seq is not null then
    select coalesce(max(id), 0) + 1 into v_max from public.raw_agum;
    perform setval(v_seq, v_max, false);
  end if;
end;
$$;

-- ─── raw_atra ─────────────────────────────────────────────────────────────────
-- raw_atra puede venir de 20260426123000 (sin identity) o de 20260429100000
-- (con identity). El DO block cubre ambos casos.

do $$
begin
  if not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname  = 'raw_atra'
      and a.attname  = 'id'
      and a.attidentity in ('d', 'a')
  ) then
    alter table public.raw_atra
      alter column id add generated by default as identity;
  end if;
end;
$$;

do $$
declare
  v_seq text;
  v_max bigint;
begin
  v_seq := pg_get_serial_sequence('public.raw_atra', 'id');
  if v_seq is not null then
    select coalesce(max(id), 0) + 1 into v_max from public.raw_atra;
    perform setval(v_seq, v_max, false);
  end if;
end;
$$;

-- ─── Unique source indexes (idempotencia en re-ingestas) ─────────────────────
-- Fallará en raw_amat/raw_agum si aún hay duplicados — verificar preflight 5a/5b.
-- raw_atra está vacía en remoto (T0.2) → no puede tener duplicados.

create unique index if not exists raw_amat_source_uidx
  on public.raw_amat(source_zip, source_file, source_row);

create unique index if not exists raw_agum_source_uidx
  on public.raw_agum(source_zip, source_file, source_row);

create unique index if not exists raw_atra_source_uidx
  on public.raw_atra(source_zip, source_file, source_row);
