-- T1.1.d -- Anexos GUMA/GUME HTML (2 tablas)
-- Non-destructive: CREATE TABLE IF NOT EXISTS, CREATE INDEX IF NOT EXISTS

-- raw_anexo_guma (52 cols)
create table if not exists public.raw_anexo_guma (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null,
  col_012 text null,
  col_013 text null,
  col_014 text null,
  col_015 text null,
  col_016 text null,
  col_017 text null,
  col_018 text null,
  col_019 text null,
  col_020 text null,
  col_021 text null,
  col_022 text null,
  col_023 text null,
  col_024 text null,
  col_025 text null,
  col_026 text null,
  col_027 text null,
  col_028 text null,
  col_029 text null,
  col_030 text null,
  col_031 text null,
  col_032 text null,
  col_033 text null,
  col_034 text null,
  col_035 text null,
  col_036 text null,
  col_037 text null,
  col_038 text null,
  col_039 text null,
  col_040 text null,
  col_041 text null,
  col_042 text null,
  col_043 text null,
  col_044 text null,
  col_045 text null,
  col_046 text null,
  col_047 text null,
  col_048 text null,
  col_049 text null,
  col_050 text null,
  col_051 text null,
  col_052 text null
);
comment on table public.raw_anexo_guma is 'anexo_guma.html / MDB#ANEXO_GUMA — A4 GUMA detalle (layout nuevo 31 cols activo, legacy 51-52). Fuente preferida sobre raw_agum. T2.2.';
create index if not exists raw_anexo_guma_periodo_idx on public.raw_anexo_guma(anio, mes);
create index if not exists raw_anexo_guma_nemo_idx on public.raw_anexo_guma(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_guma_source_uidx on public.raw_anexo_guma(source_zip, source_file, source_row);
alter table public.raw_anexo_guma enable row level security;
drop policy if exists raw_anexo_guma_sel on public.raw_anexo_guma;
create policy raw_anexo_guma_sel on public.raw_anexo_guma for select to authenticated using (true);
drop policy if exists raw_anexo_guma_adm on public.raw_anexo_guma;
create policy raw_anexo_guma_adm on public.raw_anexo_guma for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gume (34 cols)
create table if not exists public.raw_anexo_gume (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null,
  col_012 text null,
  col_013 text null,
  col_014 text null,
  col_015 text null,
  col_016 text null,
  col_017 text null,
  col_018 text null,
  col_019 text null,
  col_020 text null,
  col_021 text null,
  col_022 text null,
  col_023 text null,
  col_024 text null,
  col_025 text null,
  col_026 text null,
  col_027 text null,
  col_028 text null,
  col_029 text null,
  col_030 text null,
  col_031 text null,
  col_032 text null,
  col_033 text null,
  col_034 text null
);
comment on table public.raw_anexo_gume is 'anexo_gume.html / gume_gupa.html — A4 GUME/GUPA detalle (4 layouts segun version). T2.8.';
create index if not exists raw_anexo_gume_periodo_idx on public.raw_anexo_gume(anio, mes);
create index if not exists raw_anexo_gume_nemo_idx on public.raw_anexo_gume(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gume_source_uidx on public.raw_anexo_gume(source_zip, source_file, source_row);
alter table public.raw_anexo_gume enable row level security;
drop policy if exists raw_anexo_gume_sel on public.raw_anexo_gume;
create policy raw_anexo_gume_sel on public.raw_anexo_gume for select to authenticated using (true);
drop policy if exists raw_anexo_gume_adm on public.raw_anexo_gume;
create policy raw_anexo_gume_adm on public.raw_anexo_gume for all to authenticated using (public.is_admin()) with check (public.is_admin());
