-- T1.1.a — DTE-base TXT tables
-- Non-destructive: CREATE TABLE IF NOT EXISTS, CREATE INDEX IF NOT EXISTS
-- DROP POLICY IF EXISTS before CREATE POLICY (idempotent)
-- Preflight: run `select to_regclass('public.raw_atra')` before applying.
-- NEVER DROP TABLE on existing raw_* tables.

-- ─────────────────────────────────────────
-- raw_dte  (dteYYMM.txt, 13 cols, ~1.1M filas local)
-- ─────────────────────────────────────────
create table if not exists public.raw_dte (
  id           bigint generated by default as identity primary key,
  anio         integer not null,
  mes          integer not null check (mes between 1 and 12),
  source_zip   text    not null,
  source_file  text    not null,
  source_row   integer not null,
  section_index integer null,
  col_count    integer not null,
  raw_text     text    null,
  col_001 text null, col_002 text null, col_003 text null, col_004 text null,
  col_005 text null, col_006 text null, col_007 text null, col_008 text null,
  col_009 text null, col_010 text null, col_011 text null, col_012 text null,
  col_013 text null
);
comment on table public.raw_dte is 'Volcado posicional de dteYYMM.txt — DTE resumen económico mensual (A1..A15). Parser: T2.5 → dte_resumen_agente.';

create index if not exists raw_dte_periodo_idx      on public.raw_dte(anio, mes);
create index if not exists raw_dte_periodo_nemo_idx  on public.raw_dte(anio, mes, left(col_001, 8));
create unique index if not exists raw_dte_source_unique_idx on public.raw_dte(source_zip, source_file, source_row);

alter table public.raw_dte enable row level security;
drop policy if exists raw_dte_select_authenticated on public.raw_dte;
create policy raw_dte_select_authenticated on public.raw_dte
  for select to authenticated using (true);
drop policy if exists raw_dte_admin_all on public.raw_dte;
create policy raw_dte_admin_all on public.raw_dte
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────
-- raw_dexc  (DEXCYYMM.txt, 19 cols, ~1.3M filas local)
-- ─────────────────────────────────────────
create table if not exists public.raw_dexc (
  id           bigint generated by default as identity primary key,
  anio         integer not null,
  mes          integer not null check (mes between 1 and 12),
  source_zip   text    not null,
  source_file  text    not null,
  source_row   integer not null,
  section_index integer null,
  col_count    integer not null,
  raw_text     text    null,
  col_001 text null, col_002 text null, col_003 text null, col_004 text null,
  col_005 text null, col_006 text null, col_007 text null, col_008 text null,
  col_009 text null, col_010 text null, col_011 text null, col_012 text null,
  col_013 text null, col_014 text null, col_015 text null, col_016 text null,
  col_017 text null, col_018 text null, col_019 text null
);
comment on table public.raw_dexc is 'Volcado posicional de DEXCYYMM.txt — Anexo 11 Demanda Excedente (Res.SE 1281/06). Parser: T2.4 → excedente_mensual.';

create index if not exists raw_dexc_periodo_idx      on public.raw_dexc(anio, mes);
create index if not exists raw_dexc_periodo_nemo_idx  on public.raw_dexc(anio, mes, left(col_001, 8));
create unique index if not exists raw_dexc_source_unique_idx on public.raw_dexc(source_zip, source_file, source_row);

alter table public.raw_dexc enable row level security;
drop policy if exists raw_dexc_select_authenticated on public.raw_dexc;
create policy raw_dexc_select_authenticated on public.raw_dexc
  for select to authenticated using (true);
drop policy if exists raw_dexc_admin_all on public.raw_dexc;
create policy raw_dexc_admin_all on public.raw_dexc
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────
-- raw_atra  (ATRAYYMM.txt, 10 cols)
-- migration 20260426123000 existe en repo pero NO en remoto — se recrea aquí como IF NOT EXISTS
-- ─────────────────────────────────────────
create table if not exists public.raw_atra (
  id           bigint generated by default as identity primary key,
  anio         integer not null,
  mes          integer not null check (mes between 1 and 12),
  source_zip   text    not null,
  source_file  text    not null,
  source_row   integer not null,
  section_index integer null,
  col_count    integer not null,
  raw_text     text    null,
  col_001 text null, col_002 text null, col_003 text null, col_004 text null,
  col_005 text null, col_006 text null, col_007 text null, col_008 text null,
  col_009 text null, col_010 text null
);
comment on table public.raw_atra is 'Volcado posicional de ATRAYYMM.txt — Anexo 2 Transporte. Parser: T2.3 → transporte_concepto_mensual.';

create index if not exists raw_atra_periodo_idx      on public.raw_atra(anio, mes);
create index if not exists raw_atra_periodo_nemo_idx  on public.raw_atra(anio, mes, left(col_001, 8));
create unique index if not exists raw_atra_source_unique_idx on public.raw_atra(source_zip, source_file, source_row);

alter table public.raw_atra enable row level security;
drop policy if exists raw_atra_select_authenticated on public.raw_atra;
create policy raw_atra_select_authenticated on public.raw_atra
  for select to authenticated using (true);
drop policy if exists raw_atra_admin_all on public.raw_atra;
create policy raw_atra_admin_all on public.raw_atra
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────
-- raw_aexp  (AEXPYYMM.txt, 19 cols)
-- ─────────────────────────────────────────
create table if not exists public.raw_aexp (
  id           bigint generated by default as identity primary key,
  anio         integer not null,
  mes          integer not null check (mes between 1 and 12),
  source_zip   text    not null,
  source_file  text    not null,
  source_row   integer not null,
  section_index integer null,
  col_count    integer not null,
  raw_text     text    null,
  col_001 text null, col_002 text null, col_003 text null, col_004 text null,
  col_005 text null, col_006 text null, col_007 text null, col_008 text null,
  col_009 text null, col_010 text null, col_011 text null, col_012 text null,
  col_013 text null, col_014 text null, col_015 text null, col_016 text null,
  col_017 text null, col_018 text null, col_019 text null
);
comment on table public.raw_aexp is 'Volcado posicional de AEXPYYMM.txt — Anexo 9 Importación/Exportación. Parser: T2.12 → imp_exp_mensual.';

create index if not exists raw_aexp_periodo_idx     on public.raw_aexp(anio, mes);
create index if not exists raw_aexp_periodo_nemo_idx on public.raw_aexp(anio, mes, left(col_001, 8));
create unique index if not exists raw_aexp_source_unique_idx on public.raw_aexp(source_zip, source_file, source_row);

alter table public.raw_aexp enable row level security;
drop policy if exists raw_aexp_select_authenticated on public.raw_aexp;
create policy raw_aexp_select_authenticated on public.raw_aexp
  for select to authenticated using (true);
drop policy if exists raw_aexp_admin_all on public.raw_aexp;
create policy raw_aexp_admin_all on public.raw_aexp
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────
-- raw_agen  (AGENYYMM.txt, 25 cols, ~420k filas)
-- ─────────────────────────────────────────
create table if not exists public.raw_agen (
  id           bigint generated by default as identity primary key,
  anio         integer not null,
  mes          integer not null check (mes between 1 and 12),
  source_zip   text    not null,
  source_file  text    not null,
  source_row   integer not null,
  section_index integer null,
  col_count    integer not null,
  raw_text     text    null,
  col_001 text null, col_002 text null, col_003 text null, col_004 text null,
  col_005 text null, col_006 text null, col_007 text null, col_008 text null,
  col_009 text null, col_010 text null, col_011 text null, col_012 text null,
  col_013 text null, col_014 text null, col_015 text null, col_016 text null,
  col_017 text null, col_018 text null, col_019 text null, col_020 text null,
  col_021 text null, col_022 text null, col_023 text null, col_024 text null,
  col_025 text null
);
comment on table public.raw_agen is 'Volcado posicional de AGENYYMM.txt — Anexo 1 Generadores (incl. curva horaria A1.7). Parser: T2.10 → generacion_maquina_mensual.';

create index if not exists raw_agen_periodo_idx     on public.raw_agen(anio, mes);
create index if not exists raw_agen_periodo_nemo_idx on public.raw_agen(anio, mes, left(col_001, 8));
create unique index if not exists raw_agen_source_unique_idx on public.raw_agen(source_zip, source_file, source_row);

alter table public.raw_agen enable row level security;
drop policy if exists raw_agen_select_authenticated on public.raw_agen;
create policy raw_agen_select_authenticated on public.raw_agen
  for select to authenticated using (true);
drop policy if exists raw_agen_admin_all on public.raw_agen;
create policy raw_agen_admin_all on public.raw_agen
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────
-- raw_agfq  (AGFQYYMM.txt, 12 cols)
-- ─────────────────────────────────────────
create table if not exists public.raw_agfq (
  id           bigint generated by default as identity primary key,
  anio         integer not null,
  mes          integer not null check (mes between 1 and 12),
  source_zip   text    not null,
  source_file  text    not null,
  source_row   integer not null,
  section_index integer null,
  col_count    integer not null,
  raw_text     text    null,
  col_001 text null, col_002 text null, col_003 text null, col_004 text null,
  col_005 text null, col_006 text null, col_007 text null, col_008 text null,
  col_009 text null, col_010 text null, col_011 text null, col_012 text null
);
comment on table public.raw_agfq is 'Volcado posicional de AGFQYYMM.txt — Anexo 7 Generación Forzada/Falla Quasi-firme. Parser: T2.15.';

create index if not exists raw_agfq_periodo_idx     on public.raw_agfq(anio, mes);
create index if not exists raw_agfq_periodo_nemo_idx on public.raw_agfq(anio, mes, left(col_001, 8));
create unique index if not exists raw_agfq_source_unique_idx on public.raw_agfq(source_zip, source_file, source_row);

alter table public.raw_agfq enable row level security;
drop policy if exists raw_agfq_select_authenticated on public.raw_agfq;
create policy raw_agfq_select_authenticated on public.raw_agfq
  for select to authenticated using (true);
drop policy if exists raw_agfq_admin_all on public.raw_agfq;
create policy raw_agfq_admin_all on public.raw_agfq
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────
-- raw_aama  (AAMAYYMM.txt, 16 cols, cobertura parcial esperada)
-- ─────────────────────────────────────────
create table if not exists public.raw_aama (
  id           bigint generated by default as identity primary key,
  anio         integer not null,
  mes          integer not null check (mes between 1 and 12),
  source_zip   text    not null,
  source_file  text    not null,
  source_row   integer not null,
  section_index integer null,
  col_count    integer not null,
  raw_text     text    null,
  col_001 text null, col_002 text null, col_003 text null, col_004 text null,
  col_005 text null, col_006 text null, col_007 text null, col_008 text null,
  col_009 text null, col_010 text null, col_011 text null, col_012 text null,
  col_013 text null, col_014 text null, col_015 text null, col_016 text null
);
comment on table public.raw_aama is 'Volcado posicional de AAMAYYMM.txt — Anexo 8 Créditos/Débitos meses anteriores (reliquidaciones). Cobertura parcial: solo meses con ajustes. Parser: T2.7 → reliquidacion_mensual.';

create index if not exists raw_aama_periodo_idx     on public.raw_aama(anio, mes);
create index if not exists raw_aama_periodo_nemo_idx on public.raw_aama(anio, mes, left(col_001, 8));
create unique index if not exists raw_aama_source_unique_idx on public.raw_aama(source_zip, source_file, source_row);

alter table public.raw_aama enable row level security;
drop policy if exists raw_aama_select_authenticated on public.raw_aama;
create policy raw_aama_select_authenticated on public.raw_aama
  for select to authenticated using (true);
drop policy if exists raw_aama_admin_all on public.raw_aama;
create policy raw_aama_admin_all on public.raw_aama
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────
-- raw_rscj  (RSCJYYMM.txt, 15 cols, 57/63 meses locales)
-- ─────────────────────────────────────────
create table if not exists public.raw_rscj (
  id           bigint generated by default as identity primary key,
  anio         integer not null,
  mes          integer not null check (mes between 1 and 12),
  source_zip   text    not null,
  source_file  text    not null,
  source_row   integer not null,
  section_index integer null,
  col_count    integer not null,
  raw_text     text    null,
  col_001 text null, col_002 text null, col_003 text null, col_004 text null,
  col_005 text null, col_006 text null, col_007 text null, col_008 text null,
  col_009 text null, col_010 text null, col_011 text null, col_012 text null,
  col_013 text null, col_014 text null, col_015 text null
);
comment on table public.raw_rscj is 'Volcado posicional de RSCJYYMM.txt — Anexo 13 Cuenta Corriente GUMA↔Distribuidor (Res.Conjunta 1/2017). 57/63 meses esperados. Parser: T2.6 → cuenta_corriente_agente.';

create index if not exists raw_rscj_periodo_idx     on public.raw_rscj(anio, mes);
create index if not exists raw_rscj_periodo_nemo_idx on public.raw_rscj(anio, mes, left(col_001, 8));
create unique index if not exists raw_rscj_source_unique_idx on public.raw_rscj(source_zip, source_file, source_row);

alter table public.raw_rscj enable row level security;
drop policy if exists raw_rscj_select_authenticated on public.raw_rscj;
create policy raw_rscj_select_authenticated on public.raw_rscj
  for select to authenticated using (true);
drop policy if exists raw_rscj_admin_all on public.raw_rscj;
create policy raw_rscj_admin_all on public.raw_rscj
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────
-- raw_gudi  (GUDIYYMM.txt, 16 cols, desde 2024-03)
-- ─────────────────────────────────────────
create table if not exists public.raw_gudi (
  id           bigint generated by default as identity primary key,
  anio         integer not null,
  mes          integer not null check (mes between 1 and 12),
  source_zip   text    not null,
  source_file  text    not null,
  source_row   integer not null,
  section_index integer null,
  col_count    integer not null,
  raw_text     text    null,
  col_001 text null, col_002 text null, col_003 text null, col_004 text null,
  col_005 text null, col_006 text null, col_007 text null, col_008 text null,
  col_009 text null, col_010 text null, col_011 text null, col_012 text null,
  col_013 text null, col_014 text null, col_015 text null, col_016 text null
);
comment on table public.raw_gudi is 'Volcado posicional de GUDIYYMM.txt — Anexo 13 GUDI (Res. 976/2023). Cobertura desde 2024-03. Parser: T2.9 → gudi_detalle_mensual.';

create index if not exists raw_gudi_periodo_idx     on public.raw_gudi(anio, mes);
create index if not exists raw_gudi_periodo_nemo_idx on public.raw_gudi(anio, mes, left(col_001, 8));
create unique index if not exists raw_gudi_source_unique_idx on public.raw_gudi(source_zip, source_file, source_row);

alter table public.raw_gudi enable row level security;
drop policy if exists raw_gudi_select_authenticated on public.raw_gudi;
create policy raw_gudi_select_authenticated on public.raw_gudi
  for select to authenticated using (true);
drop policy if exists raw_gudi_admin_all on public.raw_gudi;
create policy raw_gudi_admin_all on public.raw_gudi
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────
-- raw_adis  (ADISYYMM.txt, 17 cols)
-- ─────────────────────────────────────────
create table if not exists public.raw_adis (
  id           bigint generated by default as identity primary key,
  anio         integer not null,
  mes          integer not null check (mes between 1 and 12),
  source_zip   text    not null,
  source_file  text    not null,
  source_row   integer not null,
  section_index integer null,
  col_count    integer not null,
  raw_text     text    null,
  col_001 text null, col_002 text null, col_003 text null, col_004 text null,
  col_005 text null, col_006 text null, col_007 text null, col_008 text null,
  col_009 text null, col_010 text null, col_011 text null, col_012 text null,
  col_013 text null, col_014 text null, col_015 text null, col_016 text null,
  col_017 text null
);
comment on table public.raw_adis is 'Volcado posicional de ADISYYMM.txt — Anexo 3 Distribuidores. Parser: T2.9 (junto con raw_gudi) → gudi_detalle_mensual.';

create index if not exists raw_adis_periodo_idx     on public.raw_adis(anio, mes);
create index if not exists raw_adis_periodo_nemo_idx on public.raw_adis(anio, mes, left(col_001, 8));
create unique index if not exists raw_adis_source_unique_idx on public.raw_adis(source_zip, source_file, source_row);

alter table public.raw_adis enable row level security;
drop policy if exists raw_adis_select_authenticated on public.raw_adis;
create policy raw_adis_select_authenticated on public.raw_adis
  for select to authenticated using (true);
drop policy if exists raw_adis_admin_all on public.raw_adis;
create policy raw_adis_admin_all on public.raw_adis
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────
-- raw_adco  (ADCOYYMM.txt, 8 cols)
-- ─────────────────────────────────────────
create table if not exists public.raw_adco (
  id           bigint generated by default as identity primary key,
  anio         integer not null,
  mes          integer not null check (mes between 1 and 12),
  source_zip   text    not null,
  source_file  text    not null,
  source_row   integer not null,
  section_index integer null,
  col_count    integer not null,
  raw_text     text    null,
  col_001 text null, col_002 text null, col_003 text null, col_004 text null,
  col_005 text null, col_006 text null, col_007 text null, col_008 text null
);
comment on table public.raw_adco is 'Volcado posicional de ADCOYYMM.txt — Anexo 12 Comercializadores (Res. MEyM 281-E/2017). Parser: T2.15 → cargos_comerc_mensual.';

create index if not exists raw_adco_periodo_idx     on public.raw_adco(anio, mes);
create index if not exists raw_adco_periodo_nemo_idx on public.raw_adco(anio, mes, left(col_001, 8));
create unique index if not exists raw_adco_source_unique_idx on public.raw_adco(source_zip, source_file, source_row);

alter table public.raw_adco enable row level security;
drop policy if exists raw_adco_select_authenticated on public.raw_adco;
create policy raw_adco_select_authenticated on public.raw_adco
  for select to authenticated using (true);
drop policy if exists raw_adco_admin_all on public.raw_adco;
create policy raw_adco_admin_all on public.raw_adco
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────
-- raw_auto  (AUTOYYMM.txt, 19 cols)
-- ─────────────────────────────────────────
create table if not exists public.raw_auto (
  id           bigint generated by default as identity primary key,
  anio         integer not null,
  mes          integer not null check (mes between 1 and 12),
  source_zip   text    not null,
  source_file  text    not null,
  source_row   integer not null,
  section_index integer null,
  col_count    integer not null,
  raw_text     text    null,
  col_001 text null, col_002 text null, col_003 text null, col_004 text null,
  col_005 text null, col_006 text null, col_007 text null, col_008 text null,
  col_009 text null, col_010 text null, col_011 text null, col_012 text null,
  col_013 text null, col_014 text null, col_015 text null, col_016 text null,
  col_017 text null, col_018 text null, col_019 text null
);
comment on table public.raw_auto is 'Volcado posicional de AUTOYYMM.txt — Anexo 5 Autogeneradores y Cogeneradores. Parser: T2.13 → auto_mensual.';

create index if not exists raw_auto_periodo_idx     on public.raw_auto(anio, mes);
create index if not exists raw_auto_periodo_nemo_idx on public.raw_auto(anio, mes, left(col_001, 8));
create unique index if not exists raw_auto_source_unique_idx on public.raw_auto(source_zip, source_file, source_row);

alter table public.raw_auto enable row level security;
drop policy if exists raw_auto_select_authenticated on public.raw_auto;
create policy raw_auto_select_authenticated on public.raw_auto
  for select to authenticated using (true);
drop policy if exists raw_auto_admin_all on public.raw_auto;
create policy raw_auto_admin_all on public.raw_auto
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────
-- raw_game  (GAMEYYMM.txt, 13 cols, ~477k filas)
-- ─────────────────────────────────────────
create table if not exists public.raw_game (
  id           bigint generated by default as identity primary key,
  anio         integer not null,
  mes          integer not null check (mes between 1 and 12),
  source_zip   text    not null,
  source_file  text    not null,
  source_row   integer not null,
  section_index integer null,
  col_count    integer not null,
  raw_text     text    null,
  col_001 text null, col_002 text null, col_003 text null, col_004 text null,
  col_005 text null, col_006 text null, col_007 text null, col_008 text null,
  col_009 text null, col_010 text null, col_011 text null, col_012 text null,
  col_013 text null
);
comment on table public.raw_game is 'Volcado posicional de GAMEYYMM.txt — Anexo 10 Reembolso Gastos CAMMESA. Parser: T2.10 (junto con raw_agen) → generacion_maquina_mensual.';

create index if not exists raw_game_periodo_idx     on public.raw_game(anio, mes);
create index if not exists raw_game_periodo_nemo_idx on public.raw_game(anio, mes, left(col_001, 8));
create unique index if not exists raw_game_source_unique_idx on public.raw_game(source_zip, source_file, source_row);

alter table public.raw_game enable row level security;
drop policy if exists raw_game_select_authenticated on public.raw_game;
create policy raw_game_select_authenticated on public.raw_game
  for select to authenticated using (true);
drop policy if exists raw_game_admin_all on public.raw_game;
create policy raw_game_admin_all on public.raw_game
  for all to authenticated using (public.is_admin()) with check (public.is_admin());
