-- T1.1.b -- Anexos Generacion HTML (17 tablas)
-- Non-destructive: CREATE TABLE IF NOT EXISTS, CREATE INDEX IF NOT EXISTS
-- DROP POLICY IF EXISTS before CREATE POLICY

-- raw_anexo_gen111 (18 cols)
create table if not exists public.raw_anexo_gen111 (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null,
  col_012 text null,
  col_013 text null,
  col_014 text null,
  col_015 text null,
  col_016 text null,
  col_017 text null,
  col_018 text null
);
comment on table public.raw_anexo_gen111 is 'Cuadro 11.1 Energia termica por unidad. T2.10.';
create index if not exists raw_anexo_gen111_periodo_idx on public.raw_anexo_gen111(anio, mes);
create index if not exists raw_anexo_gen111_nemo_idx on public.raw_anexo_gen111(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen111_source_uidx on public.raw_anexo_gen111(source_zip, source_file, source_row);
alter table public.raw_anexo_gen111 enable row level security;
drop policy if exists raw_anexo_gen111_sel on public.raw_anexo_gen111;
create policy raw_anexo_gen111_sel on public.raw_anexo_gen111 for select to authenticated using (true);
drop policy if exists raw_anexo_gen111_adm on public.raw_anexo_gen111;
create policy raw_anexo_gen111_adm on public.raw_anexo_gen111 for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gen112 (14 cols)
create table if not exists public.raw_anexo_gen112 (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null,
  col_012 text null,
  col_013 text null,
  col_014 text null
);
comment on table public.raw_anexo_gen112 is 'Cuadro 11.2 Potencia disponible termica. DDL 14 cols, layout activo 12. T2.10.';
create index if not exists raw_anexo_gen112_periodo_idx on public.raw_anexo_gen112(anio, mes);
create index if not exists raw_anexo_gen112_nemo_idx on public.raw_anexo_gen112(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen112_source_uidx on public.raw_anexo_gen112(source_zip, source_file, source_row);
alter table public.raw_anexo_gen112 enable row level security;
drop policy if exists raw_anexo_gen112_sel on public.raw_anexo_gen112;
create policy raw_anexo_gen112_sel on public.raw_anexo_gen112 for select to authenticated using (true);
drop policy if exists raw_anexo_gen112_adm on public.raw_anexo_gen112;
create policy raw_anexo_gen112_adm on public.raw_anexo_gen112 for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gen113 (11 cols)
create table if not exists public.raw_anexo_gen113 (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null
);
comment on table public.raw_anexo_gen113 is 'Cuadro 11.3 Energia hidraulica. T2.10.';
create index if not exists raw_anexo_gen113_periodo_idx on public.raw_anexo_gen113(anio, mes);
create index if not exists raw_anexo_gen113_nemo_idx on public.raw_anexo_gen113(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen113_source_uidx on public.raw_anexo_gen113(source_zip, source_file, source_row);
alter table public.raw_anexo_gen113 enable row level security;
drop policy if exists raw_anexo_gen113_sel on public.raw_anexo_gen113;
create policy raw_anexo_gen113_sel on public.raw_anexo_gen113 for select to authenticated using (true);
drop policy if exists raw_anexo_gen113_adm on public.raw_anexo_gen113;
create policy raw_anexo_gen113_adm on public.raw_anexo_gen113 for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gen114 (11 cols)
create table if not exists public.raw_anexo_gen114 (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null
);
comment on table public.raw_anexo_gen114 is 'Cuadro 11.4 Potencia hidraulica. DDL 11 cols, layout activo 8. T2.10.';
create index if not exists raw_anexo_gen114_periodo_idx on public.raw_anexo_gen114(anio, mes);
create index if not exists raw_anexo_gen114_nemo_idx on public.raw_anexo_gen114(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen114_source_uidx on public.raw_anexo_gen114(source_zip, source_file, source_row);
alter table public.raw_anexo_gen114 enable row level security;
drop policy if exists raw_anexo_gen114_sel on public.raw_anexo_gen114;
create policy raw_anexo_gen114_sel on public.raw_anexo_gen114 for select to authenticated using (true);
drop policy if exists raw_anexo_gen114_adm on public.raw_anexo_gen114;
create policy raw_anexo_gen114_adm on public.raw_anexo_gen114 for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gen115 (19 cols)
create table if not exists public.raw_anexo_gen115 (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null,
  col_012 text null,
  col_013 text null,
  col_014 text null,
  col_015 text null,
  col_016 text null,
  col_017 text null,
  col_018 text null,
  col_019 text null
);
comment on table public.raw_anexo_gen115 is 'Cuadro 11.5 Termica con DIGO. T2.10.';
create index if not exists raw_anexo_gen115_periodo_idx on public.raw_anexo_gen115(anio, mes);
create index if not exists raw_anexo_gen115_nemo_idx on public.raw_anexo_gen115(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen115_source_uidx on public.raw_anexo_gen115(source_zip, source_file, source_row);
alter table public.raw_anexo_gen115 enable row level security;
drop policy if exists raw_anexo_gen115_sel on public.raw_anexo_gen115;
create policy raw_anexo_gen115_sel on public.raw_anexo_gen115 for select to authenticated using (true);
drop policy if exists raw_anexo_gen115_adm on public.raw_anexo_gen115;
create policy raw_anexo_gen115_adm on public.raw_anexo_gen115 for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gen116 (6 cols)
create table if not exists public.raw_anexo_gen116 (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null
);
comment on table public.raw_anexo_gen116 is 'Cuadro 11.6 Potencia DIGO. T2.10.';
create index if not exists raw_anexo_gen116_periodo_idx on public.raw_anexo_gen116(anio, mes);
create index if not exists raw_anexo_gen116_nemo_idx on public.raw_anexo_gen116(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen116_source_uidx on public.raw_anexo_gen116(source_zip, source_file, source_row);
alter table public.raw_anexo_gen116 enable row level security;
drop policy if exists raw_anexo_gen116_sel on public.raw_anexo_gen116;
create policy raw_anexo_gen116_sel on public.raw_anexo_gen116 for select to authenticated using (true);
drop policy if exists raw_anexo_gen116_adm on public.raw_anexo_gen116;
create policy raw_anexo_gen116_adm on public.raw_anexo_gen116 for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gen117 (12 cols)
create table if not exists public.raw_anexo_gen117 (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null,
  col_012 text null
);
comment on table public.raw_anexo_gen117 is 'Cuadro 11.7 Adicionales. T2.10.';
create index if not exists raw_anexo_gen117_periodo_idx on public.raw_anexo_gen117(anio, mes);
create index if not exists raw_anexo_gen117_nemo_idx on public.raw_anexo_gen117(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen117_source_uidx on public.raw_anexo_gen117(source_zip, source_file, source_row);
alter table public.raw_anexo_gen117 enable row level security;
drop policy if exists raw_anexo_gen117_sel on public.raw_anexo_gen117;
create policy raw_anexo_gen117_sel on public.raw_anexo_gen117 for select to authenticated using (true);
drop policy if exists raw_anexo_gen117_adm on public.raw_anexo_gen117;
create policy raw_anexo_gen117_adm on public.raw_anexo_gen117 for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gen118 (10 cols)
create table if not exists public.raw_anexo_gen118 (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null
);
comment on table public.raw_anexo_gen118 is 'Cuadro 11.8. T2.10.';
create index if not exists raw_anexo_gen118_periodo_idx on public.raw_anexo_gen118(anio, mes);
create index if not exists raw_anexo_gen118_nemo_idx on public.raw_anexo_gen118(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen118_source_uidx on public.raw_anexo_gen118(source_zip, source_file, source_row);
alter table public.raw_anexo_gen118 enable row level security;
drop policy if exists raw_anexo_gen118_sel on public.raw_anexo_gen118;
create policy raw_anexo_gen118_sel on public.raw_anexo_gen118 for select to authenticated using (true);
drop policy if exists raw_anexo_gen118_adm on public.raw_anexo_gen118;
create policy raw_anexo_gen118_adm on public.raw_anexo_gen118 for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gen119 (8 cols)
create table if not exists public.raw_anexo_gen119 (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null
);
comment on table public.raw_anexo_gen119 is 'Cuadro 11.9. T2.10.';
create index if not exists raw_anexo_gen119_periodo_idx on public.raw_anexo_gen119(anio, mes);
create index if not exists raw_anexo_gen119_nemo_idx on public.raw_anexo_gen119(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen119_source_uidx on public.raw_anexo_gen119(source_zip, source_file, source_row);
alter table public.raw_anexo_gen119 enable row level security;
drop policy if exists raw_anexo_gen119_sel on public.raw_anexo_gen119;
create policy raw_anexo_gen119_sel on public.raw_anexo_gen119 for select to authenticated using (true);
drop policy if exists raw_anexo_gen119_adm on public.raw_anexo_gen119;
create policy raw_anexo_gen119_adm on public.raw_anexo_gen119 for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gen12 (18 cols)
create table if not exists public.raw_anexo_gen12 (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null,
  col_012 text null,
  col_013 text null,
  col_014 text null,
  col_015 text null,
  col_016 text null,
  col_017 text null,
  col_018 text null
);
comment on table public.raw_anexo_gen12 is 'Cuadro 12 Servicios Auxiliares potencia. T2.10.';
create index if not exists raw_anexo_gen12_periodo_idx on public.raw_anexo_gen12(anio, mes);
create index if not exists raw_anexo_gen12_nemo_idx on public.raw_anexo_gen12(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen12_source_uidx on public.raw_anexo_gen12(source_zip, source_file, source_row);
alter table public.raw_anexo_gen12 enable row level security;
drop policy if exists raw_anexo_gen12_sel on public.raw_anexo_gen12;
create policy raw_anexo_gen12_sel on public.raw_anexo_gen12 for select to authenticated using (true);
drop policy if exists raw_anexo_gen12_adm on public.raw_anexo_gen12;
create policy raw_anexo_gen12_adm on public.raw_anexo_gen12 for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gen13 (16 cols)
create table if not exists public.raw_anexo_gen13 (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null,
  col_012 text null,
  col_013 text null,
  col_014 text null,
  col_015 text null,
  col_016 text null
);
comment on table public.raw_anexo_gen13 is 'Cuadro 13 Reservas y Potencia Termica 4hs. T2.10.';
create index if not exists raw_anexo_gen13_periodo_idx on public.raw_anexo_gen13(anio, mes);
create index if not exists raw_anexo_gen13_nemo_idx on public.raw_anexo_gen13(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen13_source_uidx on public.raw_anexo_gen13(source_zip, source_file, source_row);
alter table public.raw_anexo_gen13 enable row level security;
drop policy if exists raw_anexo_gen13_sel on public.raw_anexo_gen13;
create policy raw_anexo_gen13_sel on public.raw_anexo_gen13 for select to authenticated using (true);
drop policy if exists raw_anexo_gen13_adm on public.raw_anexo_gen13;
create policy raw_anexo_gen13_adm on public.raw_anexo_gen13 for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gen_disp_mejora (12 cols)
create table if not exists public.raw_anexo_gen_disp_mejora (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null,
  col_012 text null
);
comment on table public.raw_anexo_gen_disp_mejora is 'Disponibilidad Mejorada Res. SE 1085/17. T2.11.';
create index if not exists raw_anexo_gen_disp_mejora_periodo_idx on public.raw_anexo_gen_disp_mejora(anio, mes);
create index if not exists raw_anexo_gen_disp_mejora_nemo_idx on public.raw_anexo_gen_disp_mejora(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen_disp_mejora_source_uidx on public.raw_anexo_gen_disp_mejora(source_zip, source_file, source_row);
alter table public.raw_anexo_gen_disp_mejora enable row level security;
drop policy if exists raw_anexo_gen_disp_mejora_sel on public.raw_anexo_gen_disp_mejora;
create policy raw_anexo_gen_disp_mejora_sel on public.raw_anexo_gen_disp_mejora for select to authenticated using (true);
drop policy if exists raw_anexo_gen_disp_mejora_adm on public.raw_anexo_gen_disp_mejora;
create policy raw_anexo_gen_disp_mejora_adm on public.raw_anexo_gen_disp_mejora for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_generacion_forzada (6 cols)
create table if not exists public.raw_anexo_generacion_forzada (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null
);
comment on table public.raw_anexo_generacion_forzada is 'Generacion forzada Res. SE 220. T2.11.';
create index if not exists raw_anexo_generacion_forzada_periodo_idx on public.raw_anexo_generacion_forzada(anio, mes);
create index if not exists raw_anexo_generacion_forzada_nemo_idx on public.raw_anexo_generacion_forzada(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_generacion_forzada_source_uidx on public.raw_anexo_generacion_forzada(source_zip, source_file, source_row);
alter table public.raw_anexo_generacion_forzada enable row level security;
drop policy if exists raw_anexo_generacion_forzada_sel on public.raw_anexo_generacion_forzada;
create policy raw_anexo_generacion_forzada_sel on public.raw_anexo_generacion_forzada for select to authenticated using (true);
drop policy if exists raw_anexo_generacion_forzada_adm on public.raw_anexo_generacion_forzada;
create policy raw_anexo_generacion_forzada_adm on public.raw_anexo_generacion_forzada for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gen_294pot (10 cols)
create table if not exists public.raw_anexo_gen_294pot (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null
);
comment on table public.raw_anexo_gen_294pot is 'Res. SE 294 potencia. Desde 2024-12. T2.11.';
create index if not exists raw_anexo_gen_294pot_periodo_idx on public.raw_anexo_gen_294pot(anio, mes);
create index if not exists raw_anexo_gen_294pot_nemo_idx on public.raw_anexo_gen_294pot(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen_294pot_source_uidx on public.raw_anexo_gen_294pot(source_zip, source_file, source_row);
alter table public.raw_anexo_gen_294pot enable row level security;
drop policy if exists raw_anexo_gen_294pot_sel on public.raw_anexo_gen_294pot;
create policy raw_anexo_gen_294pot_sel on public.raw_anexo_gen_294pot for select to authenticated using (true);
drop policy if exists raw_anexo_gen_294pot_adm on public.raw_anexo_gen_294pot;
create policy raw_anexo_gen_294pot_adm on public.raw_anexo_gen_294pot for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gen_294ene (11 cols)
create table if not exists public.raw_anexo_gen_294ene (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null
);
comment on table public.raw_anexo_gen_294ene is 'Res. SE 294 energia. Desde 2024-12. T2.11.';
create index if not exists raw_anexo_gen_294ene_periodo_idx on public.raw_anexo_gen_294ene(anio, mes);
create index if not exists raw_anexo_gen_294ene_nemo_idx on public.raw_anexo_gen_294ene(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gen_294ene_source_uidx on public.raw_anexo_gen_294ene(source_zip, source_file, source_row);
alter table public.raw_anexo_gen_294ene enable row level security;
drop policy if exists raw_anexo_gen_294ene_sel on public.raw_anexo_gen_294ene;
create policy raw_anexo_gen_294ene_sel on public.raw_anexo_gen_294ene for select to authenticated using (true);
drop policy if exists raw_anexo_gen_294ene_adm on public.raw_anexo_gen_294ene;
create policy raw_anexo_gen_294ene_adm on public.raw_anexo_gen_294ene for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_genmovil (15 cols)
create table if not exists public.raw_anexo_genmovil (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null,
  col_007 text null,
  col_008 text null,
  col_009 text null,
  col_010 text null,
  col_011 text null,
  col_012 text null,
  col_013 text null,
  col_014 text null,
  col_015 text null
);
comment on table public.raw_anexo_genmovil is 'Generacion movil containers. T2.11.';
create index if not exists raw_anexo_genmovil_periodo_idx on public.raw_anexo_genmovil(anio, mes);
create index if not exists raw_anexo_genmovil_nemo_idx on public.raw_anexo_genmovil(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_genmovil_source_uidx on public.raw_anexo_genmovil(source_zip, source_file, source_row);
alter table public.raw_anexo_genmovil enable row level security;
drop policy if exists raw_anexo_genmovil_sel on public.raw_anexo_genmovil;
create policy raw_anexo_genmovil_sel on public.raw_anexo_genmovil for select to authenticated using (true);
drop policy if exists raw_anexo_genmovil_adm on public.raw_anexo_genmovil;
create policy raw_anexo_genmovil_adm on public.raw_anexo_genmovil for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- raw_anexo_gennuc (6 cols)
create table if not exists public.raw_anexo_gennuc (
  id            bigint generated by default as identity  primary key,
  anio          integer not null,
  mes           integer not null check (mes between 1 and 12),
  source_zip    text    not null,
  source_file   text    not null,
  source_row    integer not null,
  section_index integer null,
  col_count     integer not null,
  raw_text      text    null,
  col_001 text null,
  col_002 text null,
  col_003 text null,
  col_004 text null,
  col_005 text null,
  col_006 text null
);
comment on table public.raw_anexo_gennuc is 'Generacion nuclear. Desde 2023-02. T2.11.';
create index if not exists raw_anexo_gennuc_periodo_idx on public.raw_anexo_gennuc(anio, mes);
create index if not exists raw_anexo_gennuc_nemo_idx on public.raw_anexo_gennuc(anio, mes, left(col_001, 8));
create unique index if not exists raw_anexo_gennuc_source_uidx on public.raw_anexo_gennuc(source_zip, source_file, source_row);
alter table public.raw_anexo_gennuc enable row level security;
drop policy if exists raw_anexo_gennuc_sel on public.raw_anexo_gennuc;
create policy raw_anexo_gennuc_sel on public.raw_anexo_gennuc for select to authenticated using (true);
drop policy if exists raw_anexo_gennuc_adm on public.raw_anexo_gennuc;
create policy raw_anexo_gennuc_adm on public.raw_anexo_gennuc for all to authenticated using (public.is_admin()) with check (public.is_admin());
